alpha: 0.5
clip:
epochs: 1000
lr: 0.001
lr_decay: step
lr_factor: 0.5
lr_schedule:
  - 1000
  - 2000
lr_throttle: True
optimizer: adam
save_period: -1
test_batch_size: 100
test_mode: default
train_batch_size: 100
train_mode: progressive
val_period: 10
warmup_period: 10