defaults:
  - hyp: _default_hyperparameters
  - problem: prefix_sums
  - model: dt_net_recall_1d
  - override hydra/job_logging: custom
  - _self_

hydra:
  run:
    dir: ./outputs/${name}/${now:%Y%m%d}-${now:%H:%M}-testing-${run_id}
  job_logging:
    handlers:
      file:
        filename: testing.log

name: testing_default

model:
  test_iterations:
    low: 30
    high: 50
  model_path: ../20211220-14:39-training-yogic-Tamora

quick_test: False

